\documentclass[a4paper]{article}

\title{GOexpress: Visualise microarray and RNAseq data using gene ontology annotations}
\author{Kevin Rue-Albrecht}

\begin{document}
\SweaveOpts{concordance=TRUE}

\maketitle

\tableofcontents

\section[Introduction]{Introduction}



In this example we embed parts of the examples from the
\texttt{kruskal.test} help page into a \LaTeX{} document:

<<>>=
data(airquality , package = "datasets")
library("stats")
kruskal.test(Ozone ~ Month , data = airquality )
@
which shows that the location parameter of the Ozone
distribution varies significantly from month to month . Finally we
include a boxplot of the data :

\begin{center}
<<fig=TRUE,echo=FALSE>>=
library("graphics")
boxplot ( Ozone ~ Month , data = airquality )
@
\end{center}

\end{document}